#bin the ubuntu verions
ARG img_digest=1030f108596afba03281f4c350466d74b900922c25e9881c7df6eefce6681080
FROM  ubuntu:20.04@sha256:${img_digest}

ARG BASE_PATH
ARG PYTHONPATH

ENV BASE_PATH=$BASE_PATH
ENV PYTHONPATH=$PYTHONPATH

RUN apt-get update && apt-get install -y  \
    git \
    wget \
    make \
    pkg-config \
    build-essential \

# Setting Python environment and installing required pacakges
ADD requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /work
CMD ["bash"]